### ISSUE TITLE
[Bug] Mod does not activate when going to skyblock

### ISSUE THREAD

**Issue by Zailer43** [xMrVizzy/Skyblocker#1]
### Expected behavior
After entering skyblock the first thing I would see would be the health bar and mana, and don't spam me the cooldown of the abilitys

### Current behavior
Only he works the menu to configure the mod, but nothing works

**Comment by Zailer43** [comment]
I already found out why it doesn't work, I'm in a CO-OP and the mod doesn't detect it
![image](https://user-images.githubusercontent.com/63565983/105611958-6f14a180-5d97-11eb-9f87-5f9a917bc5dc.png)
https://github.com/xMrVizzy/Skyblocker/blob/b851d1148c19e6daf51ed5228491777f26040442/src/main/java/me/xmrvizzy/skyblocker/utils/Utils.java#L57

**Comment by UltraBlackLinux** [comment]
change .equals to .contains - This will fix it, then just run `gradlew.bat build`

**Comment by Zailer43** [comment]
> change .equals to .contains - This will fix it, then just run `gradlew.bat build`

actually since yesterday I'm using a build that does that but with startsWith

**Comment by xMrVizzy** [comment]
oh okay fixed
