### ISSUE TITLE
1.17 support?

### ISSUE THREAD

**Issue by Teh404Gal** [xMrVizzy/Skyblocker#13]
title

**Comment by TAKfsg** [comment]
^^^^^

**Comment by MaxBr5** [comment]
<pre>You know Hypixel is stuck on 1.14</pre>

**Comment by TAKfsg** [comment]
> You know Hypixel is stuck on 1.14

then why is there a 1.16 version?

**Comment by MaxBr5** [comment]
1.14 servers work with 1.16

**Comment by MaxBr5** [comment]
clients

**Comment by MaxBr5** [comment]
<pre>They installed a compatibility layer mod with 1.16</pre>

**Comment by TAKfsg** [comment]
Theres a 1.17 fork of this mod
