### ISSUE TITLE
Healing Wands break Health bar

### ISSUE THREAD

**Issue by UltraBlackLinux** [xMrVizzy/Skyblocker#2]
![Screenshot_20210123_201314](https://user-images.githubusercontent.com/62404294/105611749-6e8c0300-5db7-11eb-8cca-99776122fc21.png)
Any Ideas?
Thanks for this great mod!

**Comment by UltraBlackLinux** [comment]
![Screenshot_20210124_111229](https://user-images.githubusercontent.com/62404294/105627129-14ca1e00-5e35-11eb-8625-6597d02cf5e9.png)
BTW: This is, how it looks w/o bars

**Comment by UltraBlackLinux** [comment]
Managed to fix it:
```
            if (section.contains("❤")) {
                split = section.split("❤");
                Attribute.HEALTH.set(Integer.parseInt(split[1]));
                Attribute.MAX_HEALTH.set(Integer.parseInt(split[2]));
```
Tested: Works
Currently no display for the healing countdown wahtsoever

**Comment by xMrVizzy** [comment]
I know how to fix this, there is another way to do it!

**Comment by xMrVizzy** [comment]
I will add it in v1.0.5
