### ISSUE TITLE
Crash when placing water

### ISSUE THREAD

**Issue by Zailer43** [xMrVizzy/Skyblocker#4]
I had previously crashed and thought it was related to #3, but as xmrvizzy says that crash is REI's I open this
Crash doesn't happen without skyblocker

### Steps to play it
1. Buy Magic Bucket of Water
2. Go to your island
3. Place water
4. Crash

[crash-2021-01-28_18.54.42-client.txt](https://github.com/xMrVizzy/Skyblocker/files/5889968/crash-2021-01-28_18.54.42-client.txt)

**Comment by UltraBlackLinux** [comment]
> I had previously crashed and thought it was related to #3, but as xmrvizzy says that crash is REI's I open this
> Crash doesn't happen without skyblocker
> ### Steps to play it
> 
>     1. Buy Magic Bucket of Water
> 
>     2. Go to your island
> 
>     3. Place water
> 
>     4. Crash
> 
> 
> [crash-2021-01-28_18.54.42-client.txt](https://github.com/xMrVizzy/Skyblocker/files/5889968/crash-2021-01-28_18.54.42-client.txt)

seems to be related to enchanted items

**Comment by xMrVizzy** [comment]
I found this null pointer, it because this code (#3):
` if (!stack.hasTag() && !stack.getTag().contains("ExtraAttributes")) return;
            CompoundTag attributes = stack.getTag().getCompound("ExtraAttributes");
            if (!attributes.contains("drill_fuel")) return;`

**Comment by xMrVizzy** [comment]
Ok, so I fixed it, will push update today

**Comment by xMrVizzy** [comment]
Fixed in v1.0.4 - https://modrinth.com/mod/skyblocker/version/okrToUiZ
