### ISSUE TITLE
Hide ability cooldown has a message that doesn't match

### ISSUE THREAD

**Issue by Zailer43** [xMrVizzy/Skyblocker#5]
#### Message:
![image](https://user-images.githubusercontent.com/63565983/106199549-5c81da00-6194-11eb-96c8-108aeb6f882a.png)
#### Skyblocker:
https://github.com/xMrVizzy/Skyblocker/blob/b851d1148c19e6daf51ed5228491777f26040442/src/main/java/me/xmrvizzy/skyblocker/mixin/ChatHudListenerMixin.java#L33-L34

**Comment by UltraBlackLinux** [comment]
I guess you can change it to `msg.contains(" cooldown")`
should be enough.
I t hink this will even hide the personal bank thing

**Comment by xMrVizzy** [comment]
Added in v1.0.4 - https://modrinth.com/mod/skyblocker/version/okrToUiZ
