### ISSUE TITLE
Defense not updated when equipping mastiff armor

### ISSUE THREAD

**Issue by Zailer43** [xMrVizzy/Skyblocker#6]
Now on the new all-in-one bar if you equip any piece or all the mastiff armor does not change the defense when it should be 0

PS: In the settings it says `Health & Mana Bars` and not `Health, Mana, Defense & XP Bars` or something

**Comment by xMrVizzy** [comment]
Hmm, I tested it with Mastif and it works for me.

**Comment by xMrVizzy** [comment]
Oh I know why. Will fix it today.

**Comment by xMrVizzy** [comment]
Fixed, redownload v1.0.4 again!
